### ISSUE TITLE
Material de estudio I1

### ISSUE THREAD

**Issue by AlfreMK** [IIC2343/Syllabus-2021-2-S2#2]
Hola!, me preguntaba dónde podía encontrar interrogaciones pasadas, guías, o algo de índole similar para estudiar por la i1 de este martes. Ojalá si es material que se asemeje harto al tipo de preguntas o materia que pueden preguntar (valga la redundancia) el martes.

**Comment by frvalenzuela** [comment]
¡ Hola @AlfreMK  !

Puedes encontrar un compilado de pruebas de semestres anteriores en el siguiente [link](https://github.com/IIC2343/Syllabus-anteriores/blob/main/Enunciados/Compilado_IIC2343.pdf).

Este fue un compilado hecho el primer semestre del año pasado, y tiene una varidad de preguntas del curso desde el año 2011 hasta el año 2018, abarcando interrogaciones y examenes. 

A lo largo de la historia el curso ha tenido varios profesores con distinto tipo de enfoque en las preguntas, por lo que no podría garantizarte que este material tenga preguntas que se asemejen a lo que verán en la interrogación de este martes. Lo que si puedo confirmarte es que en documento existen preguntas de toda la materia del curso, incluyendo los contenidos que el profesor reviso en clases, por lo que es un gran complemento para su estudio.

Si te queda alguna pregunta no dudes en decirme.

¡ Saludos !

**Comment by AlfreMK** [comment]
Gracias Felipe te pasaste!
