### ISSUE TITLE
Adder

### ISSUE THREAD

**Issue by M-Altamirano** [IIC2343/Syllabus-2021-2-S2#20]
Hola! En el enunciado dice que el Adder debe sumarle 1 al PC, pero solo tiene conectado un bus de 12 '1'. Puede interpretarse como que en realidad es un bus con un 1 representado en 12 bits?

Gracias!

**Comment by Allmoz** [comment]
Hola, efectivamente es eso, es un 1 representado en 12 bits.

**Comment by M-Altamirano** [comment]
Gracias!
