### ISSUE TITLE
Estudio I1

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2343/Syllabus-2021-2-S2#3]
Buenas tardes,
Quería consultar hasta que clase o materia entra en la I1?
Saludos

**Comment by jtconcha** [comment]
Sumándome a la pregunta, ¿Hay algún temario para la I1?
Gracias de antemano!

**Comment by frvalenzuela** [comment]
¡ Hola @AlonsoZamorano  @jtconcha !

Entra hasta lo que se vio el día jueves 23 de Septiembre incluido. Esto quiere decir:

- Representación de datos
- Lógica, circuitos, operaciones
- Programabilidad
- Saltos
- Subrutinas
- Todo lo relacionado al computador básico, incluyendo el como programar en assembler en el computador básico

Si queda alguna pregunta no duden en decirme. 😄 

¡ Saludos !

**Comment by Allmoz** [comment]
Si, corresponde a los 2 primeros capítulos descritos en el programa del curso.
