### ISSUE TITLE
Duda temario examen

### ISSUE THREAD

**Issue by sbersanii** [IIC2343/Syllabus-2021-2-S2#40]
Hola, 

¿El último tema que entra en el examen entonces es paralelismo a nivel de instrucción?.
Porque en los apuntes existentes hay uno de "paralelismo avanzado", entonces no se si entra también.

Saludos atentos

**Comment by Allmoz** [comment]
Hola,

Si, la taxonomía de Flynn fue lo que vimos el martes antepasado, faltaba subir las diapositivas, gracias.

Saludos.

**Comment by sbersanii** [comment]
Gracias profesor!
